### ISSUE TITLE
E: Invalid Release file, no entry for main/binary-i386/Packages

### ISSUE THREAD

**Issue by jeremiah** [lkorigin/debspawn#1]
Running this command;
```
$ debspawn create green
```
Produces this output;
```
╔═════════════════════════════════════════╗
║  Creating new base: green [i386]        ║
╚═════════════════════════════════════════╝
Using mirror: default
Bootstrap suite: green

┌───────────────────┐
│  Bootstrap        │
└───────────────────┘
I: Retrieving InRelease 
I: Checking Release signature
I: Valid Release signature (key id 0D6695569A8253FF9C389F552B4A53F2B41CE072)
E: Invalid Release file, no entry for main/binary-i386/Packages
```

Environment;
debootstrap 1.0.89
Debian GNU/Linux 9.9 (stretch)

**Comment by ximion** [comment]
This is not a bug in Debspawn. The distribution (PureOS) does not have an i386 flavor, so downloading it fails.
By default, if no architecture is specified, Debspawn will use the architecture of the host to create a new environment, which in this case seems to be i386.
You can override this by passing the `--arch` parameter: `debspawn create green --arch amd64`

Feel free to reopen the issue report if this reply doesn't make sense to you or the issue persists.

**Comment by jeremiah** [comment]
Sure enough, passed the amd64 arch and everything just worked.
