### ISSUE TITLE
ModuleNotFoundError: No module named 'debspawn'

### ISSUE THREAD

**Issue by jeremiah** [lkorigin/debspawn#2]
Recently upgraded from stretch to buster and got this error;

Traceback (most recent call last):
  File "/usr/local/bin/debspawn", line 5, in <module>
    from debspawn import cli
ModuleNotFoundError: No module named 'debspawn'

I reinstalled debspawn and the error went away.

**Comment by ximion** [comment]
You closing it means you probably found out that the error hinted at Debspawn installed manually into /usr/local? ;-)
(I guess the problem was just Python being confused on what to import here, or due to a Python upgrade the software would have had to be reinstalled)

**Comment by jeremiah** [comment]
I opened the bug once I saw the error, but I kept it open in my browser until I could confirm it was a real bug. I think it is as you say, a python upgrade not finding the module for some reason. I reinstalled and am running it now with no issues. :^)
