### ISSUE TITLE
Feature request: extra package/repository when building

### ISSUE THREAD

**Issue by zhsj** [lkorigin/debspawn#5]
like sbuild `--extra-package=package.deb` and `--extra-repository=spec`.

**Comment by ximion** [comment]
This one is already on my todo list with a pretty high priority, because I needed this myself a couple of times (and it was also originally planned).
I'll be away for more than three weeks, but will look into this afterwards.

**Comment by ximion** [comment]
Injecting packages is really easy now, you just need to copy them to `/var/lib/debspawn/injected-pkgs/`. I may also add a flag to set a location from the command-line though, as that could be useful as well.
