### ISSUE TITLE
Feature request: option not to run debian/rules clean 

### ISSUE THREAD

**Issue by zhsj** [lkorigin/debspawn#6]
like sbuild `--no-clean-source`.

This is useful when used with gbp. So you don't need to install build-depends on host.

**Comment by cdluminate** [comment]
Seconded. Being able to trigger a build without requiring the build dependencies on the host system is quite useful (especially when a package has a ton of dependency packages).

https://github.com/lkorigin/debspawn/blob/master/debspawn/build.py#L202

And maybe we could add some other customizations here as well.

**Comment by ximion** [comment]
> So you don't need to install build-depends on host.

I think this is already the default, because the `-d` flag is passed when generating the source package.
But yeah, customizing this more makes sense to me (and with `-d`, the clean rule is still executed AFAIR).

**Comment by cdluminate** [comment]
what we meant is the -nc, i.e. the --no-clean option for dpkg-buildpackage. I have patched build.py locally to implement this.

**Comment by ximion** [comment]
Indeed! That may even be something for the next release (to be out soon).

**Comment by ximion** [comment]
I went the opposite route here: The no-clean option is the new default, replacing the "ignore all dependencies" mode used previously. The package gets cleaned again anyway once it has been copied into the container environment.
To restore the previous behavior, pass `--clean-source` to debspawn to have it invoke d/rules clean on the host environment as well.
