### ISSUE TITLE
Feature Request: Post-build lintian check

### ISSUE THREAD

**Issue by cdluminate** [lkorigin/debspawn#9]

**Comment by ximion** [comment]
if you pass `--lintian` to debspawn, it will now run Lintian post-build. There's one caveat: If Lintian fails its analysis, no artifacts will be returned (not sure if that's a good thing or a bad thing, but it is consistent at least with the existing behavior).

Debspawn will always use the Lintian from the container, to ensure the package is validated with a validator that is appropriate for the environment the package was built for.
